### ISSUE TITLE
How to use TrackerHub with ByteTrack + custom yolov5 models?

### ISSUE THREAD

**Issue by madenbr** [kadirnar/TrackerHub#12]
```
TRACKER_CONFIG:
    # The name of the tracker
    TRACKER_TYPE: BYTE_TRACK                 <--
    # The path of the config file
    CONFIG_PATH: trackerhub/configs/byte_track.yaml    <--
    # The path of the model file
    WEIGHT_PATH: osnet_x1_0_msmt17.pt


DETECTOR_CONFIG:
  # The name of the detector
  DETECTOR_TYPE: yolov5 # yolov7
  # The threshold for the IOU score
  IOU_TH: 0.45
  # The threshold for the confidence score
  CONF_TH: 0.25
  # The size of the image
  IMAGE_SIZE: 640
  # The path of the weight file
  WEIGHT_PATH: D:/best.pt                        <--
  # The device to run the detector
  DEVICE: cpu #cuda:0
  # F16 precision
  HALF: False

VIDEO_CONFIG:
  # The path of the input video
  INPUT_PATH: D:/test.mp4                      <--
  # The path of the output video
  OUTPUT_PATH: Results
  # Save the video
  SAVE_VIDEO: True 
```

I edited `default_config.yaml` as like above. I saw this line of code ` frame, tracker=True, yaml_file="trackerhub/configs/yolov6/coco.yaml"`. Should I change this yaml file by my custom dedection yaml file. Also,  How will I change TRACKER WEIGHT_PATH section.

What are the things that I need to edit?
